Repository wooahan-agile/idu-market-react, pull requests merged in 2021-04, with the labels that each got.

#123 [login] Login , id 찾기 ,pw 찾기 UI수정
  src/components/Header/Header.js
  src/components/auth/FindIdComponent.js
  src/components/auth/FindPasswordComponent.js
  src/components/auth/LoginComponent.js
  src/container/HeaderMenuData.js
  src/scss/layout/_header.scss
Labels: 리액트, 스타일링

#125 [hit] Hit
  src/components/Boards/Detail/BoardDetailComponent.js
  src/container/HeaderMenuData.js
  src/redux/reducers/boardsReducer.js
  src/redux/sagas/boardsSaga.js
  src/redux/types.js
Labels: 리액트

#131 [modal] Modal 제거
  src/components/Boards/Update/PostUpdateComponent.js
  src/components/Boards/Write/PostWriteComponent.js
  src/redux/sagas/boardsSaga.js
Labels: 리액트, 스타일링

#133 [img] Img
  src/components/Header/Header.js
  src/components/HomePage/Section/FunctionComponent.js
  src/components/HomePage/Section/MainBannerComponent.js
  src/scss/layout/_footer.scss
Labels: 리액트

#134 [fix]Fix
  src/components/Editor/EditorConfig.js
  src/components/Editor/UploadAdapter.js
  src/components/HomePage/Section/MainBannerComponent.js
  src/redux/sagas/authSaga.js
  src/redux/sagas/boardsSaga.js
  src/scss/layout/home/_funtion.scss
  src/scss/layout/home/_mainBanner.scss
Labels: 리액트, 스타일링

#136 [basicBoard] basicBoard 깨짐현상 수정 #135
  package-lock.json
  src/components/Boards/Basic/BasicBoardComponent.js
  src/scss/layout/boards/_basic.scss
Labels: 스타일링

#137 [notice]Notice
  src/components/Boards/Write/PostWriteComponent.js
  src/scss/layout/home/_notice.scss
Labels: 리액트

#140 [favicon]Favicon
  public/favicon.ico
Labels: 리액트, 스타일링

#141 [fix] Fix
  src/redux/reducers/authReducer.js
  src/redux/sagas/authSaga.js
Labels: 리액트
