Repository wooahan-agile/idu-market-react, pull requests merged in 2021-03, with the labels that each got.

#45 [findPassword] findPassword Page UI 및 기능 구현
  package.json
  src/components/auth/FindIdComponent.js
  src/components/auth/FindPasswordComponent.js
  src/scss/layout/_forms.scss
Labels: 리액트

#58 [inifinite]: Inifinite 구현
  src/components/Boards/BoardListItem.js
  src/components/Boards/BookListComponent.js
  src/components/Boards/Layout/BoardBanner.js
  src/components/Boards/Layout/SearchComponent.js
  src/components/Boards/Market/BookListComponent.js
  src/components/Boards/Market/ClothesListComponent.js
  src/components/Boards/Market/DeviceListComponent.js
  src/components/Boards/Write/PostWriteComponent.js
  src/container/BoardItemData.js
  src/pages/Boards/Market/BookListPage.js
  src/pages/Boards/Market/ClothesListPage.js
  src/pages/Boards/Market/DeviceListPage.js
  src/pages/Boards/PostWritePage.js
  src/pages/Boards/Write/PostWritePage.js
  src/pages/MainRouter.js
  src/scss/layout/boards/_market.scss
Labels: 리액트, 스타일링

#59 [freeBoard] FreeBoard Redux 구현#54
  package-lock.json
  package.json
  src/components/Boards/FreeBoardComponent.js
  src/components/Boards/NoticeBoardComponent.js
  src/pages/Boards/FreeBoardPage.js
  src/pages/Boards/NoticeBoardPage.js
  src/pages/MainRouter.js
  src/redux/reducers/marketReducer.js
  src/redux/sagas/marketSaga.js
  src/redux/types.js
  src/scss/layout/boards/_board.scss
  src/scss/main.scss
Labels: 리액트, 스타일링

#66 [infiniteScroll] infiniteScroll 클래스형에서 함수형으로 변환
  src/components/Boards/Market/BookListComponent.js
  src/components/Boards/Market/ClothesListComponent.js
  src/components/Boards/Market/DeviceListComponent.js
Labels: 리액트

#67 [postWrite] postWrite 구현
  src/components/Boards/Market/BookListComponent.js
  src/components/Boards/Market/ClothesListComponent.js
  src/components/Boards/Market/DeviceListComponent.js
  src/components/Boards/Write/PostWriteComponent.js
  src/components/auth/FindIdComponent.js
  src/redux/reducers/boardNewReducer.js
  src/redux/reducers/index.js
  src/redux/sagas/boardNewSaga.js
  src/redux/sagas/index.js
  src/redux/types.js
  src/scss/layout/_forms.scss
  src/scss/layout/boards/_market.scss
  src/scss/layout/boards/_postWrite.scss
Labels: 리액트

#69 [ConnectReactRouter] ConnectReactRouter 구현
  package.json
  src/App.js
  src/components/Boards/Basic/FreeBoardComponent.js
  src/components/Boards/Basic/NoticeBoardComponent.js
  src/components/Boards/Write/PostWriteComponent.js
  src/components/auth/LoginComponent.js
  src/components/auth/RegisterComponent.js
  src/components/auth/loadingUser.js
  src/index.js
  src/pages/MainRouter.js
  src/redux/reducers/BoardsReducer.js
  src/redux/reducers/authReducer.js
  src/redux/reducers/boardNewReducer.js
  src/redux/reducers/index.js
  src/redux/sagas/authSaga.js
  src/redux/sagas/boardNewSaga.js
  src/redux/sagas/boardsSaga.js
  src/redux/sagas/index.js
  src/redux/types.js
  src/store.js
  yarn.lock
Labels: 리액트, 스타일링

#71 [profile] Profile UI,Redux 기능 구현
  src/components/Profile/ProfileComponent.js
  src/redux/reducers/index.js
  src/redux/sagas/index.js
  src/redux/sagas/profileSaga.js
Labels: 리액트, 스타일링

#73 [boardDetail]Board detail 구현
  src/components/Boards/Basic/FreeBoardComponent.js
  src/components/Boards/Basic/NoticeBoardComponent.js
  src/components/Boards/Basic/SearchComponent.js
  src/components/Boards/BoardListItem.js
  src/components/Boards/Detail/BoardDetailComponent.js
  src/components/Boards/Detail/BoardDetailTop.js
  src/components/Boards/Market/BookListComponent.js
  src/components/Boards/Market/ClothesListComponent.js
  src/components/Boards/Market/DeviceListComponent.js
  src/components/Boards/Write/PostWriteComponent.js
  src/components/HomePage/Section/ArticlesComponent.js
  src/pages/Boards/Detail/BoardDetailPage.js
  src/pages/MainRouter.js
  src/redux/reducers/BoardsReducer.js
  src/redux/reducers/boardNewReducer.js
  src/redux/reducers/boardsReducer.js
  src/redux/reducers/index.js
  src/redux/sagas/boardNewSaga.js
  src/redux/sagas/boardsSaga.js
  src/redux/sagas/index.js
  src/redux/types.js
  src/scss/layout/boards/_boardDetail.scss
  src/scss/layout/boards/_boardNew.scss
  src/scss/main.scss
Labels: 리액트, 스타일링

#75 [BasicBoard]Basic Board Update
  src/components/Boards/Basic/FreeBoardComponent.js
  src/components/Boards/Basic/NoticeBoardComponent.js
  src/components/Boards/BoardListItem.js
  src/components/Boards/Write/PostWriteComponent.js
Labels: 리액트, 스타일링

#76 [basicfreeboard] basicfreeboard UI수정
  src/redux/sagas/profileSaga.js
  src/scss/layout/boards/_basic.scss
Labels: 스타일링

#78 [marketCombine] Market List Combine
  src/components/Boards/BoardListItem.js
  src/components/Boards/Market/ClothesListComponent.js
  src/components/Boards/Market/DeviceListComponent.js
  src/components/Boards/Market/MarketListComponent.js
  src/pages/Boards/Market/BookListPage.js
  src/pages/Boards/Market/ClothesListPage.js
  src/pages/Boards/Market/DeviceListPage.js
Labels: 리액트

#81 [basicBoardLoading] basicBoardLoading 기능 추가
  src/components/Boards/Basic/FreeBoardComponent.js
  src/components/Boards/Basic/NoticeBoardComponent.js
  src/components/Watchlist/WatchlistBtnComponent.js
  src/components/Watchlist/WatchlistPageComponent.js
  src/pages/MainRouter.js
  src/pages/WatchlistPage/WatchlistPage.js
  src/scss/layout/boards/_basic.scss
  src/scss/layout/watchlist/_watchlist.scss
  src/scss/main.scss
Labels: 리액트

#94 [commnet] comment 로그인 유무에 따른 생성 가능 여부 구현
  src/components/Boards/Comment/CommentComponent.js
  src/components/Boards/Comment/SingleComment.js
  src/scss/layout/boards/_comment.scss
Labels: 리액트, 스타일링

#95 [comment]Comment 반응형 UI 구현
  src/components/Boards/BoardListItem.js
  src/components/Boards/Search/SearchListComponent.js
  src/scss/layout/boards/_comment.scss
  src/scss/layout/boards/_market.scss
Labels: 리액트, 스타일링

#97 [scrollToTop]: ScrollToTop 기능 구현
  src/components/ScrollToTop.js
  src/pages/MainRouter.js
Labels: 리액트, 스타일링

#98 [market] Market
  src/components/Boards/Detail/BoardDetailTop.js
  src/scss/layout/boards/_boardWrite.scss
  src/scss/layout/boards/_market.scss
Labels: 리액트, 스타일링

#100 [header] Header UI Update
  src/components/Header/DropMenu.js
  src/components/Header/Header.js
  src/components/Profile/ProfileComponent.js
  src/pages/MainRouter.js
  src/scss/layout/_header.scss
  src/scss/layout/boards/_basic.scss
Labels: 리액트, 스타일링

#112 [codeSplitting] Code Splitting 적용
  src/components/Boards/Market/MarketListComponent.js
  src/components/Watchlist/WatchlistComponent.js
  src/components/purchaseAndSaleList/PurchaseListComponent.js
  src/components/purchaseAndSaleList/SaleListComponent.js
  src/pages/LoadingPage.js
  src/pages/MainRouter.js
  src/redux/sagas/boardsSaga.js
  src/scss/main.scss
  src/scss/page/_loading.scss
Labels: 리액트

#114 [404] 404Page 구현
  src/pages/MainRouter.js
  src/pages/Page404.js
  src/scss/main.scss
  src/scss/page/_404.scss
Labels: 리액트, 스타일링

#116 [register] Register 폼 유효성검사
  src/components/auth/RegisterComponent.js
  src/scss/layout/_forms.scss
  src/scss/layout/boards/_boardWrite.scss
  src/scss/page/_404.scss
Labels: 리액트, 스타일링

#117 [register]Register 반응형 UI
  src/components/auth/RegisterComponent.js
  src/scss/layout/_forms.scss
Labels: 리액트, 스타일링

#119 [profileImg] Profile img
  src/components/Boards/BoardListItem.js
  src/components/Boards/Comment/ReplyComment.js
  src/components/Boards/Comment/SingleComment.js
  src/components/Boards/Detail/BoardDetailTop.js
  src/redux/reducers/boardsReducer.js
  src/redux/sagas/boardsSaga.js
  src/redux/sagas/commentSaga.js
  src/scss/layout/boards/_basic.scss
  src/scss/layout/boards/_boardDetail.scss
  src/scss/layout/boards/_comment.scss
  src/scss/layout/boards/_market.scss
Labels: 리액트, 스타일링

#120 fix(sangjun/register): register 유효성검사 수정#115
  src/components/auth/RegisterComponent.js
Labels: 리액트, 스타일링

#121 [postWrite]Post Write
  src/components/Boards/Basic/BasicBoardComponent.js
  src/components/Boards/BoardListItem.js
  src/components/Boards/Detail/BoardDetailTop.js
  src/components/Boards/Market/MarketListComponent.js
  src/components/Boards/Write/PostWriteComponent.js
  src/components/Editor/EditorConfig.js
  src/components/Editor/UploadAdapter.js
  src/components/Profile/ProfileComponent.js
  src/components/auth/RegisterComponent.js
  src/components/trade/TradeCompleteComponent.js
  src/hoc/auth.js
  src/pages/MainRouter.js
  src/redux/reducers/boardsReducer.js
  src/redux/reducers/profileReducer.js
  src/redux/reducers/tradeReducer.js
  src/redux/sagas/boardsSaga.js
  src/redux/sagas/tradeSaga.js
Labels: 리액트, 스타일링
